//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureProto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public Datum()
        {
            this.Data1 = new HashSet<Datum>();
        }
    
        public int BlobTestId { get; set; }
        public System.Guid TestGuid { get; set; }
        public string Name { get; set; }
        public byte[] Data { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string FileName { get; set; }
        public bool IsFolder { get; set; }
    
        public virtual ICollection<Datum> Data1 { get; set; }
        public virtual Datum Datum1 { get; set; }
    }
}
